version: '3.8'

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./frontend:/app 
      - /app/node_modules 
    command: npm run serve
    networks:
      - agronetwork

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://ywd:YWDa351656@rm-cn-jeo3nfa850005obo.rwlb.zhangbei.rds.aliyuncs.com:5001/Farmland data
    ports:
      - "8888:8888"
    networks:
      - agronetwork

networks:
  agronetwork:
    external: true
